# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

threshold_detection_impl <- function(audio_samples, sample_rate, threshold, min_d, max_d, min_TBE, max_TBE, EDG, LPF, HPF, dur_t, snr_t, angl_t, FFT_size, FFT_overlap, start_t, end_t, NWS, KPE, KME) {
    .Call(`_bioacoustics_threshold_detection_impl`, audio_samples, sample_rate, threshold, min_d, max_d, min_TBE, max_TBE, EDG, LPF, HPF, dur_t, snr_t, angl_t, FFT_size, FFT_overlap, start_t, end_t, NWS, KPE, KME)
}

blob_detection_impl <- function(audio_samples, sample_rate, FFT_size, FFT_overlap, min_TBE, max_TBE, HPF, LPF, min_d, max_d, area, blur_f, bg_substract, EDG, boost) {
    .Call(`_bioacoustics_blob_detection_impl`, audio_samples, sample_rate, FFT_size, FFT_overlap, min_TBE, max_TBE, HPF, LPF, min_d, max_d, area, blur_f, bg_substract, EDG, boost)
}

read_wac_impl <- function(filepath, filename) {
    .Call(`_bioacoustics_read_wac_impl`, filepath, filename)
}

.fspec_impl <- function(audio_samples, fft_size, fft_overlap, win, HPF_bin, LPF_bin, FLL_bin, FUL_bin, rotate) {
    .Call(`_bioacoustics_fspec_impl`, audio_samples, fft_size, fft_overlap, win, HPF_bin, LPF_bin, FLL_bin, FUL_bin, rotate)
}

